# Generated by Django 5.2 on 2025-04-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('size', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.equipment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.organization')),
            ],
        ),
    ]
