# Generated by Django 5.2.1 on 2025-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleForApproving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wannabe_role', models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('teacher', 'Преподаватель')], max_length=30)),
            ],
        ),
    ]
